#!/usr/bin/env bash                                                             
#start apache2 inside docker                                                     
service apache2 start
echo 'Hello Holberton' > /var/www/html/index.html
sudo service apache2 start
